# Generated by Django 3.2.9 on 2021-11-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time_start', models.TimeField()),
                ('Time_end', models.TimeField()),
                ('is_group', models.BooleanField(default=False)),
            ],
        ),
    ]
