# Generated by Django 3.2.9 on 2021-11-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
        ('abonement', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='Time_end',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='Time_start',
            new_name='time_start',
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abonement.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abonement.employees'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('achievements', models.TextField()),
                ('id_methodic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examination.methodic')),
                ('id_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_clients', models.ManyToManyField(to='abonement.Client')),
            ],
        ),
    ]
