# Generated by Django 3.2.9 on 2021-12-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonement', '0003_auto_20211226_2347'),
        ('training', '0002_alter_group_id_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id_trainer',
            field=models.ForeignKey(limit_choices_to={'profession': 't'}, on_delete=django.db.models.deletion.CASCADE, to='abonement.employees', verbose_name='Trainer'),
        ),
    ]
