# Generated by Django 3.2.9 on 2021-11-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonement', '0002_auto_20211125_1425'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('training', '0002_auto_20211118_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='is_group',
        ),
        migrations.AddField(
            model_name='schedule',
            name='object_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_trainer',
            field=models.ForeignKey(limit_choices_to={'profession': 't'}, on_delete=django.db.models.deletion.CASCADE, to='abonement.employees'),
        ),
    ]
