# Generated by Django 3.2.9 on 2021-11-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20211125_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='training_type',
            new_name='content_type',
        ),
    ]
