# Generated by Django 3.2.9 on 2021-12-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_schedule_id_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='id_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='training.schedule'),
        ),
    ]
