# Generated by Django 3.2.9 on 2021-12-22 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examination', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField()),
                ('imt', models.FloatField()),
                ('fat_percentage', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('recommendation', models.TextField(max_length=500)),
                ('result_of_examination', models.TextField(max_length=500)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonement.client')),
                ('id_employ', models.ForeignKey(limit_choices_to={'profession': 'd'}, on_delete=django.db.models.deletion.PROTECT, to='abonement.employees')),
            ],
            options={
                'verbose_name': 'Result of examination',
                'ordering': ['date_examination'],
            },
        ),
        migrations.CreateModel(
            name='Methodic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodic', models.TextField(max_length=63)),
                ('id_examination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examination.examination')),
            ],
            options={
                'verbose_name': 'Methodic of training',
                'ordering': ['methodic'],
            },
        ),
    ]
