# Generated by Django 3.2.9 on 2021-11-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examination', models.DateField()),
                ('weight', models.FloatField()),
                ('imt', models.FloatField()),
                ('fat_percentage', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('recomendation', models.TextField(max_length=500)),
                ('result_of_examination', models.TextField(max_length=500)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonement.client')),
                ('id_employ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonement.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Methodic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodic', models.TextField(max_length=63)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonement.client')),
                ('id_examination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examination.examination')),
            ],
        ),
    ]
