# Generated by Django 3.2.9 on 2021-11-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonement', '0002_auto_20211125_1425'),
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='recomendation',
            new_name='recommendation',
        ),
        migrations.RemoveField(
            model_name='methodic',
            name='id_client',
        ),
        migrations.AlterField(
            model_name='examination',
            name='date_examination',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='id_employ',
            field=models.ForeignKey(limit_choices_to={'profession': 'd'}, on_delete=django.db.models.deletion.PROTECT, to='abonement.employees'),
        ),
    ]
