# Generated by Django 3.2.9 on 2021-12-23 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pool', models.BooleanField(default=False)),
                ('spa_zone', models.BooleanField(default=False)),
                ('training_type', models.CharField(choices=[('p', 'personal'), ('g', 'group')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('surname', models.CharField(max_length=63)),
                ('patronymic', models.CharField(max_length=63)),
                ('date_of_birthday', models.DateField()),
                ('sex', models.CharField(choices=[('m', 'man'), ('w', 'woman'), ('t', 'they')], max_length=1)),
                ('address', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
                ('profession', models.CharField(choices=[('t', 'trainer'), ('d', 'doctor')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.CharField(blank=True, choices=[('m', 'man'), ('w', 'woman'), ('t', 'they')], max_length=1)),
                ('phone_number', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('num_of_trainings', models.IntegerField()),
                ('price', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonement.client')),
                ('trainer_id', models.ForeignKey(limit_choices_to={'profession': 't'}, on_delete=django.db.models.deletion.PROTECT, to='abonement.employees')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonement.abonementtype')),
            ],
        ),
    ]
