# Generated by Django 3.2.9 on 2021-11-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonements',
            name='trainer_id',
            field=models.ForeignKey(limit_choices_to={'profession': 't'}, on_delete=django.db.models.deletion.PROTECT, to='abonement.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='profession',
            field=models.CharField(choices=[('t', 'trainer'), ('d', 'doctor')], max_length=1),
        ),
    ]
