# Generated by Django 3.2.9 on 2021-12-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonement', '0002_remove_abonements_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonements',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonement.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='abonements',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='abonements',
            name='trainer_id',
            field=models.ForeignKey(limit_choices_to={'profession': 't'}, on_delete=django.db.models.deletion.PROTECT, to='abonement.employees', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='abonements',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonement.abonementtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
