# Generated by Django 3.2.9 on 2021-12-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonement', '0004_auto_20211229_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonements',
            name='trainer_id',
        ),
    ]
